/* eslint-disable react-refresh/only-export-components */
import type { Metadata } from 'next';
import './globals.css';
import { Provider } from './provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='antialiased light'>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
