/* eslint-disable react-refresh/only-export-components */
import { Menu } from '@/components/Menu';
import type { Metadata } from 'next';
import './globals.css';
import { Provider } from './provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <body>
        <Provider>{children}</Provider>

        <Menu />
      </body>
    </html>
  );
}
