// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/root9464/Ton-students/ent/predicate"
	"github.com/root9464/Ton-students/ent/service"
	"github.com/root9464/Ton-students/ent/servicetag"
	"github.com/root9464/Ton-students/ent/tags"
)

// ServiceTagQuery is the builder for querying ServiceTag entities.
type ServiceTagQuery struct {
	config
	ctx         *QueryContext
	order       []servicetag.OrderOption
	inters      []Interceptor
	predicates  []predicate.ServiceTag
	withService *ServiceQuery
	withTag     *TagsQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ServiceTagQuery builder.
func (stq *ServiceTagQuery) Where(ps ...predicate.ServiceTag) *ServiceTagQuery {
	stq.predicates = append(stq.predicates, ps...)
	return stq
}

// Limit the number of records to be returned by this query.
func (stq *ServiceTagQuery) Limit(limit int) *ServiceTagQuery {
	stq.ctx.Limit = &limit
	return stq
}

// Offset to start from.
func (stq *ServiceTagQuery) Offset(offset int) *ServiceTagQuery {
	stq.ctx.Offset = &offset
	return stq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (stq *ServiceTagQuery) Unique(unique bool) *ServiceTagQuery {
	stq.ctx.Unique = &unique
	return stq
}

// Order specifies how the records should be ordered.
func (stq *ServiceTagQuery) Order(o ...servicetag.OrderOption) *ServiceTagQuery {
	stq.order = append(stq.order, o...)
	return stq
}

// QueryService chains the current query on the "service" edge.
func (stq *ServiceTagQuery) QueryService() *ServiceQuery {
	query := (&ServiceClient{config: stq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := stq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := stq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(servicetag.Table, servicetag.FieldID, selector),
			sqlgraph.To(service.Table, service.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, servicetag.ServiceTable, servicetag.ServiceColumn),
		)
		fromU = sqlgraph.SetNeighbors(stq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTag chains the current query on the "tag" edge.
func (stq *ServiceTagQuery) QueryTag() *TagsQuery {
	query := (&TagsClient{config: stq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := stq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := stq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(servicetag.Table, servicetag.FieldID, selector),
			sqlgraph.To(tags.Table, tags.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, servicetag.TagTable, servicetag.TagColumn),
		)
		fromU = sqlgraph.SetNeighbors(stq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ServiceTag entity from the query.
// Returns a *NotFoundError when no ServiceTag was found.
func (stq *ServiceTagQuery) First(ctx context.Context) (*ServiceTag, error) {
	nodes, err := stq.Limit(1).All(setContextOp(ctx, stq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{servicetag.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (stq *ServiceTagQuery) FirstX(ctx context.Context) *ServiceTag {
	node, err := stq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ServiceTag ID from the query.
// Returns a *NotFoundError when no ServiceTag ID was found.
func (stq *ServiceTagQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = stq.Limit(1).IDs(setContextOp(ctx, stq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{servicetag.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (stq *ServiceTagQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := stq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ServiceTag entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ServiceTag entity is found.
// Returns a *NotFoundError when no ServiceTag entities are found.
func (stq *ServiceTagQuery) Only(ctx context.Context) (*ServiceTag, error) {
	nodes, err := stq.Limit(2).All(setContextOp(ctx, stq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{servicetag.Label}
	default:
		return nil, &NotSingularError{servicetag.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (stq *ServiceTagQuery) OnlyX(ctx context.Context) *ServiceTag {
	node, err := stq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ServiceTag ID in the query.
// Returns a *NotSingularError when more than one ServiceTag ID is found.
// Returns a *NotFoundError when no entities are found.
func (stq *ServiceTagQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = stq.Limit(2).IDs(setContextOp(ctx, stq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{servicetag.Label}
	default:
		err = &NotSingularError{servicetag.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (stq *ServiceTagQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := stq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ServiceTags.
func (stq *ServiceTagQuery) All(ctx context.Context) ([]*ServiceTag, error) {
	ctx = setContextOp(ctx, stq.ctx, ent.OpQueryAll)
	if err := stq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ServiceTag, *ServiceTagQuery]()
	return withInterceptors[[]*ServiceTag](ctx, stq, qr, stq.inters)
}

// AllX is like All, but panics if an error occurs.
func (stq *ServiceTagQuery) AllX(ctx context.Context) []*ServiceTag {
	nodes, err := stq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ServiceTag IDs.
func (stq *ServiceTagQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if stq.ctx.Unique == nil && stq.path != nil {
		stq.Unique(true)
	}
	ctx = setContextOp(ctx, stq.ctx, ent.OpQueryIDs)
	if err = stq.Select(servicetag.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (stq *ServiceTagQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := stq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (stq *ServiceTagQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, stq.ctx, ent.OpQueryCount)
	if err := stq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, stq, querierCount[*ServiceTagQuery](), stq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (stq *ServiceTagQuery) CountX(ctx context.Context) int {
	count, err := stq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (stq *ServiceTagQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, stq.ctx, ent.OpQueryExist)
	switch _, err := stq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (stq *ServiceTagQuery) ExistX(ctx context.Context) bool {
	exist, err := stq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ServiceTagQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (stq *ServiceTagQuery) Clone() *ServiceTagQuery {
	if stq == nil {
		return nil
	}
	return &ServiceTagQuery{
		config:      stq.config,
		ctx:         stq.ctx.Clone(),
		order:       append([]servicetag.OrderOption{}, stq.order...),
		inters:      append([]Interceptor{}, stq.inters...),
		predicates:  append([]predicate.ServiceTag{}, stq.predicates...),
		withService: stq.withService.Clone(),
		withTag:     stq.withTag.Clone(),
		// clone intermediate query.
		sql:  stq.sql.Clone(),
		path: stq.path,
	}
}

// WithService tells the query-builder to eager-load the nodes that are connected to
// the "service" edge. The optional arguments are used to configure the query builder of the edge.
func (stq *ServiceTagQuery) WithService(opts ...func(*ServiceQuery)) *ServiceTagQuery {
	query := (&ServiceClient{config: stq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	stq.withService = query
	return stq
}

// WithTag tells the query-builder to eager-load the nodes that are connected to
// the "tag" edge. The optional arguments are used to configure the query builder of the edge.
func (stq *ServiceTagQuery) WithTag(opts ...func(*TagsQuery)) *ServiceTagQuery {
	query := (&TagsClient{config: stq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	stq.withTag = query
	return stq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (stq *ServiceTagQuery) GroupBy(field string, fields ...string) *ServiceTagGroupBy {
	stq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ServiceTagGroupBy{build: stq}
	grbuild.flds = &stq.ctx.Fields
	grbuild.label = servicetag.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (stq *ServiceTagQuery) Select(fields ...string) *ServiceTagSelect {
	stq.ctx.Fields = append(stq.ctx.Fields, fields...)
	sbuild := &ServiceTagSelect{ServiceTagQuery: stq}
	sbuild.label = servicetag.Label
	sbuild.flds, sbuild.scan = &stq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ServiceTagSelect configured with the given aggregations.
func (stq *ServiceTagQuery) Aggregate(fns ...AggregateFunc) *ServiceTagSelect {
	return stq.Select().Aggregate(fns...)
}

func (stq *ServiceTagQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range stq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, stq); err != nil {
				return err
			}
		}
	}
	for _, f := range stq.ctx.Fields {
		if !servicetag.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if stq.path != nil {
		prev, err := stq.path(ctx)
		if err != nil {
			return err
		}
		stq.sql = prev
	}
	return nil
}

func (stq *ServiceTagQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ServiceTag, error) {
	var (
		nodes       = []*ServiceTag{}
		withFKs     = stq.withFKs
		_spec       = stq.querySpec()
		loadedTypes = [2]bool{
			stq.withService != nil,
			stq.withTag != nil,
		}
	)
	if stq.withService != nil || stq.withTag != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, servicetag.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ServiceTag).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ServiceTag{config: stq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, stq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := stq.withService; query != nil {
		if err := stq.loadService(ctx, query, nodes, nil,
			func(n *ServiceTag, e *Service) { n.Edges.Service = e }); err != nil {
			return nil, err
		}
	}
	if query := stq.withTag; query != nil {
		if err := stq.loadTag(ctx, query, nodes, nil,
			func(n *ServiceTag, e *Tags) { n.Edges.Tag = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (stq *ServiceTagQuery) loadService(ctx context.Context, query *ServiceQuery, nodes []*ServiceTag, init func(*ServiceTag), assign func(*ServiceTag, *Service)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ServiceTag)
	for i := range nodes {
		if nodes[i].service_tag_service == nil {
			continue
		}
		fk := *nodes[i].service_tag_service
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(service.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "service_tag_service" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (stq *ServiceTagQuery) loadTag(ctx context.Context, query *TagsQuery, nodes []*ServiceTag, init func(*ServiceTag), assign func(*ServiceTag, *Tags)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ServiceTag)
	for i := range nodes {
		if nodes[i].service_tag_tag == nil {
			continue
		}
		fk := *nodes[i].service_tag_tag
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(tags.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "service_tag_tag" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (stq *ServiceTagQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := stq.querySpec()
	_spec.Node.Columns = stq.ctx.Fields
	if len(stq.ctx.Fields) > 0 {
		_spec.Unique = stq.ctx.Unique != nil && *stq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, stq.driver, _spec)
}

func (stq *ServiceTagQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(servicetag.Table, servicetag.Columns, sqlgraph.NewFieldSpec(servicetag.FieldID, field.TypeUUID))
	_spec.From = stq.sql
	if unique := stq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if stq.path != nil {
		_spec.Unique = true
	}
	if fields := stq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, servicetag.FieldID)
		for i := range fields {
			if fields[i] != servicetag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := stq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := stq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := stq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := stq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (stq *ServiceTagQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(stq.driver.Dialect())
	t1 := builder.Table(servicetag.Table)
	columns := stq.ctx.Fields
	if len(columns) == 0 {
		columns = servicetag.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if stq.sql != nil {
		selector = stq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if stq.ctx.Unique != nil && *stq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range stq.predicates {
		p(selector)
	}
	for _, p := range stq.order {
		p(selector)
	}
	if offset := stq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := stq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ServiceTagGroupBy is the group-by builder for ServiceTag entities.
type ServiceTagGroupBy struct {
	selector
	build *ServiceTagQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (stgb *ServiceTagGroupBy) Aggregate(fns ...AggregateFunc) *ServiceTagGroupBy {
	stgb.fns = append(stgb.fns, fns...)
	return stgb
}

// Scan applies the selector query and scans the result into the given value.
func (stgb *ServiceTagGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, stgb.build.ctx, ent.OpQueryGroupBy)
	if err := stgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ServiceTagQuery, *ServiceTagGroupBy](ctx, stgb.build, stgb, stgb.build.inters, v)
}

func (stgb *ServiceTagGroupBy) sqlScan(ctx context.Context, root *ServiceTagQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(stgb.fns))
	for _, fn := range stgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*stgb.flds)+len(stgb.fns))
		for _, f := range *stgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*stgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := stgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ServiceTagSelect is the builder for selecting fields of ServiceTag entities.
type ServiceTagSelect struct {
	*ServiceTagQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sts *ServiceTagSelect) Aggregate(fns ...AggregateFunc) *ServiceTagSelect {
	sts.fns = append(sts.fns, fns...)
	return sts
}

// Scan applies the selector query and scans the result into the given value.
func (sts *ServiceTagSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sts.ctx, ent.OpQuerySelect)
	if err := sts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ServiceTagQuery, *ServiceTagSelect](ctx, sts.ServiceTagQuery, sts, sts.inters, v)
}

func (sts *ServiceTagSelect) sqlScan(ctx context.Context, root *ServiceTagQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sts.fns))
	for _, fn := range sts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
