// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/root9464/Ton-students/ent/predicate"
	"github.com/root9464/Ton-students/ent/service"
)

// ServiceUpdate is the builder for updating Service entities.
type ServiceUpdate struct {
	config
	hooks    []Hook
	mutation *ServiceMutation
}

// Where appends a list predicates to the ServiceUpdate builder.
func (su *ServiceUpdate) Where(ps ...predicate.Service) *ServiceUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetUserName sets the "userName" field.
func (su *ServiceUpdate) SetUserName(s string) *ServiceUpdate {
	su.mutation.SetUserName(s)
	return su
}

// SetNillableUserName sets the "userName" field if the given value is not nil.
func (su *ServiceUpdate) SetNillableUserName(s *string) *ServiceUpdate {
	if s != nil {
		su.SetUserName(*s)
	}
	return su
}

// SetTitle sets the "title" field.
func (su *ServiceUpdate) SetTitle(s string) *ServiceUpdate {
	su.mutation.SetTitle(s)
	return su
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (su *ServiceUpdate) SetNillableTitle(s *string) *ServiceUpdate {
	if s != nil {
		su.SetTitle(*s)
	}
	return su
}

// SetDescription sets the "description" field.
func (su *ServiceUpdate) SetDescription(m map[string]interface{}) *ServiceUpdate {
	su.mutation.SetDescription(m)
	return su
}

// SetTags sets the "tags" field.
func (su *ServiceUpdate) SetTags(s []string) *ServiceUpdate {
	su.mutation.SetTags(s)
	return su
}

// AppendTags appends s to the "tags" field.
func (su *ServiceUpdate) AppendTags(s []string) *ServiceUpdate {
	su.mutation.AppendTags(s)
	return su
}

// SetPrice sets the "price" field.
func (su *ServiceUpdate) SetPrice(i int16) *ServiceUpdate {
	su.mutation.ResetPrice()
	su.mutation.SetPrice(i)
	return su
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (su *ServiceUpdate) SetNillablePrice(i *int16) *ServiceUpdate {
	if i != nil {
		su.SetPrice(*i)
	}
	return su
}

// AddPrice adds i to the "price" field.
func (su *ServiceUpdate) AddPrice(i int16) *ServiceUpdate {
	su.mutation.AddPrice(i)
	return su
}

// Mutation returns the ServiceMutation object of the builder.
func (su *ServiceUpdate) Mutation() *ServiceMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *ServiceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *ServiceUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *ServiceUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *ServiceUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *ServiceUpdate) check() error {
	if v, ok := su.mutation.UserName(); ok {
		if err := service.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "userName", err: fmt.Errorf(`ent: validator failed for field "Service.userName": %w`, err)}
		}
	}
	if v, ok := su.mutation.Title(); ok {
		if err := service.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Service.title": %w`, err)}
		}
	}
	return nil
}

func (su *ServiceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(service.Table, service.Columns, sqlgraph.NewFieldSpec(service.FieldID, field.TypeInt64))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.UserName(); ok {
		_spec.SetField(service.FieldUserName, field.TypeString, value)
	}
	if value, ok := su.mutation.Title(); ok {
		_spec.SetField(service.FieldTitle, field.TypeString, value)
	}
	if value, ok := su.mutation.Description(); ok {
		_spec.SetField(service.FieldDescription, field.TypeJSON, value)
	}
	if value, ok := su.mutation.Tags(); ok {
		_spec.SetField(service.FieldTags, field.TypeJSON, value)
	}
	if value, ok := su.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, service.FieldTags, value)
		})
	}
	if value, ok := su.mutation.Price(); ok {
		_spec.SetField(service.FieldPrice, field.TypeInt16, value)
	}
	if value, ok := su.mutation.AddedPrice(); ok {
		_spec.AddField(service.FieldPrice, field.TypeInt16, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{service.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// ServiceUpdateOne is the builder for updating a single Service entity.
type ServiceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServiceMutation
}

// SetUserName sets the "userName" field.
func (suo *ServiceUpdateOne) SetUserName(s string) *ServiceUpdateOne {
	suo.mutation.SetUserName(s)
	return suo
}

// SetNillableUserName sets the "userName" field if the given value is not nil.
func (suo *ServiceUpdateOne) SetNillableUserName(s *string) *ServiceUpdateOne {
	if s != nil {
		suo.SetUserName(*s)
	}
	return suo
}

// SetTitle sets the "title" field.
func (suo *ServiceUpdateOne) SetTitle(s string) *ServiceUpdateOne {
	suo.mutation.SetTitle(s)
	return suo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (suo *ServiceUpdateOne) SetNillableTitle(s *string) *ServiceUpdateOne {
	if s != nil {
		suo.SetTitle(*s)
	}
	return suo
}

// SetDescription sets the "description" field.
func (suo *ServiceUpdateOne) SetDescription(m map[string]interface{}) *ServiceUpdateOne {
	suo.mutation.SetDescription(m)
	return suo
}

// SetTags sets the "tags" field.
func (suo *ServiceUpdateOne) SetTags(s []string) *ServiceUpdateOne {
	suo.mutation.SetTags(s)
	return suo
}

// AppendTags appends s to the "tags" field.
func (suo *ServiceUpdateOne) AppendTags(s []string) *ServiceUpdateOne {
	suo.mutation.AppendTags(s)
	return suo
}

// SetPrice sets the "price" field.
func (suo *ServiceUpdateOne) SetPrice(i int16) *ServiceUpdateOne {
	suo.mutation.ResetPrice()
	suo.mutation.SetPrice(i)
	return suo
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (suo *ServiceUpdateOne) SetNillablePrice(i *int16) *ServiceUpdateOne {
	if i != nil {
		suo.SetPrice(*i)
	}
	return suo
}

// AddPrice adds i to the "price" field.
func (suo *ServiceUpdateOne) AddPrice(i int16) *ServiceUpdateOne {
	suo.mutation.AddPrice(i)
	return suo
}

// Mutation returns the ServiceMutation object of the builder.
func (suo *ServiceUpdateOne) Mutation() *ServiceMutation {
	return suo.mutation
}

// Where appends a list predicates to the ServiceUpdate builder.
func (suo *ServiceUpdateOne) Where(ps ...predicate.Service) *ServiceUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *ServiceUpdateOne) Select(field string, fields ...string) *ServiceUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Service entity.
func (suo *ServiceUpdateOne) Save(ctx context.Context) (*Service, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *ServiceUpdateOne) SaveX(ctx context.Context) *Service {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *ServiceUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *ServiceUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *ServiceUpdateOne) check() error {
	if v, ok := suo.mutation.UserName(); ok {
		if err := service.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "userName", err: fmt.Errorf(`ent: validator failed for field "Service.userName": %w`, err)}
		}
	}
	if v, ok := suo.mutation.Title(); ok {
		if err := service.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Service.title": %w`, err)}
		}
	}
	return nil
}

func (suo *ServiceUpdateOne) sqlSave(ctx context.Context) (_node *Service, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(service.Table, service.Columns, sqlgraph.NewFieldSpec(service.FieldID, field.TypeInt64))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Service.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, service.FieldID)
		for _, f := range fields {
			if !service.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != service.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.UserName(); ok {
		_spec.SetField(service.FieldUserName, field.TypeString, value)
	}
	if value, ok := suo.mutation.Title(); ok {
		_spec.SetField(service.FieldTitle, field.TypeString, value)
	}
	if value, ok := suo.mutation.Description(); ok {
		_spec.SetField(service.FieldDescription, field.TypeJSON, value)
	}
	if value, ok := suo.mutation.Tags(); ok {
		_spec.SetField(service.FieldTags, field.TypeJSON, value)
	}
	if value, ok := suo.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, service.FieldTags, value)
		})
	}
	if value, ok := suo.mutation.Price(); ok {
		_spec.SetField(service.FieldPrice, field.TypeInt16, value)
	}
	if value, ok := suo.mutation.AddedPrice(); ok {
		_spec.AddField(service.FieldPrice, field.TypeInt16, value)
	}
	_node = &Service{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{service.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
