// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/root9464/Ton-students/ent/predicate"
	"github.com/root9464/Ton-students/ent/servicetag"
	"github.com/root9464/Ton-students/ent/tags"
)

// TagsUpdate is the builder for updating Tags entities.
type TagsUpdate struct {
	config
	hooks    []Hook
	mutation *TagsMutation
}

// Where appends a list predicates to the TagsUpdate builder.
func (tu *TagsUpdate) Where(ps ...predicate.Tags) *TagsUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetTagName sets the "tagName" field.
func (tu *TagsUpdate) SetTagName(s string) *TagsUpdate {
	tu.mutation.SetTagName(s)
	return tu
}

// SetNillableTagName sets the "tagName" field if the given value is not nil.
func (tu *TagsUpdate) SetNillableTagName(s *string) *TagsUpdate {
	if s != nil {
		tu.SetTagName(*s)
	}
	return tu
}

// AddServiceTagIDs adds the "service_tags" edge to the ServiceTag entity by IDs.
func (tu *TagsUpdate) AddServiceTagIDs(ids ...uuid.UUID) *TagsUpdate {
	tu.mutation.AddServiceTagIDs(ids...)
	return tu
}

// AddServiceTags adds the "service_tags" edges to the ServiceTag entity.
func (tu *TagsUpdate) AddServiceTags(s ...*ServiceTag) *TagsUpdate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tu.AddServiceTagIDs(ids...)
}

// Mutation returns the TagsMutation object of the builder.
func (tu *TagsUpdate) Mutation() *TagsMutation {
	return tu.mutation
}

// ClearServiceTags clears all "service_tags" edges to the ServiceTag entity.
func (tu *TagsUpdate) ClearServiceTags() *TagsUpdate {
	tu.mutation.ClearServiceTags()
	return tu
}

// RemoveServiceTagIDs removes the "service_tags" edge to ServiceTag entities by IDs.
func (tu *TagsUpdate) RemoveServiceTagIDs(ids ...uuid.UUID) *TagsUpdate {
	tu.mutation.RemoveServiceTagIDs(ids...)
	return tu
}

// RemoveServiceTags removes "service_tags" edges to ServiceTag entities.
func (tu *TagsUpdate) RemoveServiceTags(s ...*ServiceTag) *TagsUpdate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tu.RemoveServiceTagIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TagsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TagsUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TagsUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TagsUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TagsUpdate) check() error {
	if v, ok := tu.mutation.TagName(); ok {
		if err := tags.TagNameValidator(v); err != nil {
			return &ValidationError{Name: "tagName", err: fmt.Errorf(`ent: validator failed for field "Tags.tagName": %w`, err)}
		}
	}
	return nil
}

func (tu *TagsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(tags.Table, tags.Columns, sqlgraph.NewFieldSpec(tags.FieldID, field.TypeUUID))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.TagName(); ok {
		_spec.SetField(tags.FieldTagName, field.TypeString, value)
	}
	if tu.mutation.ServiceTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tags.ServiceTagsTable,
			Columns: []string{tags.ServiceTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicetag.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedServiceTagsIDs(); len(nodes) > 0 && !tu.mutation.ServiceTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tags.ServiceTagsTable,
			Columns: []string{tags.ServiceTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicetag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.ServiceTagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tags.ServiceTagsTable,
			Columns: []string{tags.ServiceTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicetag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tags.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TagsUpdateOne is the builder for updating a single Tags entity.
type TagsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TagsMutation
}

// SetTagName sets the "tagName" field.
func (tuo *TagsUpdateOne) SetTagName(s string) *TagsUpdateOne {
	tuo.mutation.SetTagName(s)
	return tuo
}

// SetNillableTagName sets the "tagName" field if the given value is not nil.
func (tuo *TagsUpdateOne) SetNillableTagName(s *string) *TagsUpdateOne {
	if s != nil {
		tuo.SetTagName(*s)
	}
	return tuo
}

// AddServiceTagIDs adds the "service_tags" edge to the ServiceTag entity by IDs.
func (tuo *TagsUpdateOne) AddServiceTagIDs(ids ...uuid.UUID) *TagsUpdateOne {
	tuo.mutation.AddServiceTagIDs(ids...)
	return tuo
}

// AddServiceTags adds the "service_tags" edges to the ServiceTag entity.
func (tuo *TagsUpdateOne) AddServiceTags(s ...*ServiceTag) *TagsUpdateOne {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tuo.AddServiceTagIDs(ids...)
}

// Mutation returns the TagsMutation object of the builder.
func (tuo *TagsUpdateOne) Mutation() *TagsMutation {
	return tuo.mutation
}

// ClearServiceTags clears all "service_tags" edges to the ServiceTag entity.
func (tuo *TagsUpdateOne) ClearServiceTags() *TagsUpdateOne {
	tuo.mutation.ClearServiceTags()
	return tuo
}

// RemoveServiceTagIDs removes the "service_tags" edge to ServiceTag entities by IDs.
func (tuo *TagsUpdateOne) RemoveServiceTagIDs(ids ...uuid.UUID) *TagsUpdateOne {
	tuo.mutation.RemoveServiceTagIDs(ids...)
	return tuo
}

// RemoveServiceTags removes "service_tags" edges to ServiceTag entities.
func (tuo *TagsUpdateOne) RemoveServiceTags(s ...*ServiceTag) *TagsUpdateOne {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return tuo.RemoveServiceTagIDs(ids...)
}

// Where appends a list predicates to the TagsUpdate builder.
func (tuo *TagsUpdateOne) Where(ps ...predicate.Tags) *TagsUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TagsUpdateOne) Select(field string, fields ...string) *TagsUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Tags entity.
func (tuo *TagsUpdateOne) Save(ctx context.Context) (*Tags, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TagsUpdateOne) SaveX(ctx context.Context) *Tags {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TagsUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TagsUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TagsUpdateOne) check() error {
	if v, ok := tuo.mutation.TagName(); ok {
		if err := tags.TagNameValidator(v); err != nil {
			return &ValidationError{Name: "tagName", err: fmt.Errorf(`ent: validator failed for field "Tags.tagName": %w`, err)}
		}
	}
	return nil
}

func (tuo *TagsUpdateOne) sqlSave(ctx context.Context) (_node *Tags, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tags.Table, tags.Columns, sqlgraph.NewFieldSpec(tags.FieldID, field.TypeUUID))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tags.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tags.FieldID)
		for _, f := range fields {
			if !tags.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tags.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.TagName(); ok {
		_spec.SetField(tags.FieldTagName, field.TypeString, value)
	}
	if tuo.mutation.ServiceTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tags.ServiceTagsTable,
			Columns: []string{tags.ServiceTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicetag.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedServiceTagsIDs(); len(nodes) > 0 && !tuo.mutation.ServiceTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tags.ServiceTagsTable,
			Columns: []string{tags.ServiceTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicetag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.ServiceTagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tags.ServiceTagsTable,
			Columns: []string{tags.ServiceTagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(servicetag.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Tags{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tags.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
