// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ServicesColumns holds the columns for the "services" table.
	ServicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "title", Type: field.TypeString, Size: 2147483647},
		{Name: "description", Type: field.TypeJSON},
		{Name: "tags", Type: field.TypeJSON},
		{Name: "price", Type: field.TypeInt16},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// ServicesTable holds the schema information for the "services" table.
	ServicesTable = &schema.Table{
		Name:       "services",
		Columns:    ServicesColumns,
		PrimaryKey: []*schema.Column{ServicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "services_users_services",
				Columns:    []*schema.Column{ServicesColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "firstname", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "lastname", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "nickname", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "selected_name", Type: field.TypeEnum, Enums: []string{"firstname", "lastname", "nickname", "username"}, Default: "username"},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"user", "creator", "moderator", "administrator"}, Default: "user"},
		{Name: "info", Type: field.TypeJSON},
		{Name: "is_premium", Type: field.TypeBool, Default: false},
		{Name: "hash", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ServicesTable,
		UsersTable,
	}
)

func init() {
	ServicesTable.ForeignKeys[0].RefTable = UsersTable
}
