// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 2147483647},
		{Name: "first_name", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "last_name", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"user", "creator", "moderator", "administrator"}, Default: "user"},
		{Name: "info", Type: field.TypeJSON},
		{Name: "is_premium", Type: field.TypeBool, Default: false},
		{Name: "hash", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
